# Generated by Django 5.1.6 on 2025-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('cleaned_isi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField()),
            ],
        ),
    ]
